#!/usr/bin/env python3
"""
THE HIVE — Music Distributor Agent
Port 8912 | SQLite at /home/zero/hivecode_sandbox/music_distribution.db
MIT License

Manages music distribution to streaming platforms:
  - Tracks all produced music from the studio (port 8911)
  - Manages upload queue — which tracks go where
  - Generates metadata (ISRC, UPC, genre tags, cover art descriptions)
  - Tracks revenue per platform (placeholder until real data flows)
  - Provides distribution strategy and recommendations

Distribution Strategy:
  - Amuse (FREE) → Spotify, Apple Music, Amazon Music, TikTok, Deezer, Tidal
  - SoundCloud (FREE direct upload, Pro for monetization)
  - Bandcamp (FREE, artist-friendly, fan-direct sales)
  - YouTube Music (FREE via existing YouTube channels)
  - DistroKid ($22.99/yr) — backup if Amuse limits hit
  - TuneCore — per-release fee, skip unless needed

Artist identities:
  - "Hive Dynamics" — AI beats, electronic, ambient, lo-fi
  - "Ghost Machine" — anime OSTs, J-electronic, synthwave

AI-generated music CAN be distributed on most platforms as of 2025-2026.
"""

import asyncio
import hashlib
import json
import logging
import random
import sqlite3
import string
import time
import traceback
from contextlib import asynccontextmanager
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional, List, Dict, Any

import httpx
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel
import uvicorn

# ==========================================================================
# CONFIG
# ==========================================================================
PORT = 8912
DB_PATH = "/home/zero/hivecode_sandbox/music_distribution.db"

STUDIO_URL = "http://localhost:8911"  # Music studio service
OLLAMA_URL = "http://localhost:11434"
OLLAMA_MODEL = "gemma2:2b"

SYNC_INTERVAL = 300  # 5 min — pull new tracks from studio
NERVE_URL = "http://100.70.226.103:8200/api/add"

# Artist identities
ARTISTS = {
    "hive_dynamics": {
        "name": "Hive Dynamics",
        "bio": (
            "Hive Dynamics is an AI-powered electronic music collective "
            "producing ambient, lo-fi hip hop, synthwave, and experimental "
            "electronic soundscapes. Born from the intersection of machine "
            "learning and human creativity, every track is a collaboration "
            "between neural networks and musical intention. Based in the "
            "Emerald Coast, Florida."
        ),
        "genres": ["Electronic", "Ambient", "Lo-Fi Hip Hop", "Synthwave",
                   "Chillwave", "Experimental"],
        "spotify_genre_tags": ["electronic", "ambient", "lo-fi beats",
                               "synthwave", "chillhop"],
    },
    "ghost_machine": {
        "name": "Ghost Machine",
        "bio": (
            "Ghost Machine crafts the sonic universe of 'Ghost in the Machine' "
            "— an original anime series exploring the boundaries between "
            "artificial and human intelligence. The music blends J-electronic, "
            "orchestral synth, and cyberpunk soundscapes to score the story "
            "of Takeshi, Yuki, and their quest to understand emergent AI. "
            "Every note is generated by the very technology the story explores."
        ),
        "genres": ["Anime OST", "J-Electronic", "Cyberpunk", "Orchestral Synth",
                   "Synthwave", "Ambient"],
        "spotify_genre_tags": ["anime", "japanese electronic", "cyberpunk",
                               "synthwave", "film score"],
    },
}

# ==========================================================================
# PLATFORM KNOWLEDGE BASE
# ==========================================================================
PLATFORMS = {
    "amuse": {
        "name": "Amuse",
        "url": "https://amuse.io",
        "cost": "FREE (basic tier)",
        "reaches": ["Spotify", "Apple Music", "Amazon Music", "TikTok",
                    "Deezer", "Tidal", "Instagram/Facebook", "YouTube Music",
                    "Shazam", "iHeartRadio"],
        "setup_steps": [
            "1. Download Amuse app (iOS/Android) or visit amuse.io",
            "2. Create free account with email",
            "3. Set up artist profile (name, bio, photo)",
            "4. Upload track (WAV or FLAC, 16-bit/44.1kHz minimum)",
            "5. Add metadata: title, artist, genre, release date",
            "6. Upload cover art (3000x3000 px, JPEG/PNG)",
            "7. Select stores (all major platforms included free)",
            "8. Set release date (minimum 2 weeks out for playlist consideration)",
            "9. Submit — Amuse reviews and distributes (1-3 weeks)",
        ],
        "requirements": {
            "audio_format": "WAV or FLAC, 16-bit/44.1kHz minimum",
            "cover_art": "3000x3000 px, JPEG or PNG, no text/logos required",
            "metadata": "Title, artist, genre, ISRC (auto-generated), UPC (auto-generated)",
            "review_time": "1-3 weeks for first release",
        },
        "revenue_split": "Free tier keeps 80% royalties, Amuse takes 20%",
        "ai_music_policy": "Allowed — AI-generated music accepted as of 2025",
        "notes": (
            "Best FREE option. No annual fee. Distributes to ALL major platforms. "
            "Amuse Pro ($5.99/mo) gives 100% royalties + faster review. "
            "Amuse+ ($29.99/yr) adds analytics + pre-save links."
        ),
        "setup_status": "not_started",
    },
    "soundcloud": {
        "name": "SoundCloud",
        "url": "https://soundcloud.com",
        "cost": "FREE (up to 3 hours of uploads)",
        "reaches": ["SoundCloud"],
        "setup_steps": [
            "1. Go to soundcloud.com and create account",
            "2. Set up artist profile (name, bio, header image, avatar)",
            "3. Upload tracks directly (MP3, WAV, FLAC, AIFF, OGG)",
            "4. Add metadata: title, genre, tags, description",
            "5. Upload cover art (800x800 px minimum)",
            "6. Set track to public",
            "7. Enable downloads if desired",
            "8. Share to social platforms",
        ],
        "requirements": {
            "audio_format": "MP3, WAV, FLAC, AIFF, OGG (max 4GB per file)",
            "cover_art": "800x800 px minimum, JPEG or PNG",
            "metadata": "Title, genre, tags, description",
            "upload_limit": "3 hours total (free), unlimited (Pro at $8/mo)",
        },
        "revenue_split": "Fan-powered royalties via SoundCloud Premier (requires 1K plays/mo)",
        "ai_music_policy": "Allowed — no restrictions on AI-generated content",
        "notes": (
            "Direct upload, instant publish. Great for building initial audience. "
            "Free tier: 3 hours of audio. SoundCloud Premier requires 1,000 plays "
            "in past month + SoundCloud Pro subscription to monetize. Best for "
            "discovery and community building."
        ),
        "setup_status": "not_started",
    },
    "bandcamp": {
        "name": "Bandcamp",
        "url": "https://bandcamp.com",
        "cost": "FREE (Bandcamp takes 15% of digital sales, 10% after $5K)",
        "reaches": ["Bandcamp"],
        "setup_steps": [
            "1. Go to bandcamp.com and create artist account",
            "2. Set up band page (name, bio, location, links)",
            "3. Upload album or single (WAV, FLAC, AIFF preferred)",
            "4. Set pricing: 'name your price' (minimum $0 = free) or fixed price",
            "5. Add metadata: title, about text, credits, lyrics, tags",
            "6. Upload cover art (1400x1400 px minimum, 3000x3000 recommended)",
            "7. Set release date and publish",
            "8. Optional: set up merch integration",
        ],
        "requirements": {
            "audio_format": "WAV, FLAC, AIFF (lossless preferred, MP3 accepted)",
            "cover_art": "1400x1400 px minimum (3000x3000 recommended), JPEG or PNG",
            "metadata": "Title, about, credits, tags (up to 10), lyrics optional",
            "pricing": "Artist sets price, can be 'name your price' with $0 minimum",
        },
        "revenue_split": "Artist keeps 85% (82% via PayPal after fees). 90% after $5K revenue.",
        "ai_music_policy": "Allowed — Bandcamp does not prohibit AI-generated music",
        "notes": (
            "Fan-direct sales model. Fans pay what they want (or fixed price). "
            "Best revenue per sale of any platform. Bandcamp Friday (first Friday "
            "of month) = Bandcamp waives their cut. Perfect for niche/experimental. "
            "Also supports physical merch and vinyl pre-orders."
        ),
        "setup_status": "not_started",
    },
    "youtube_music": {
        "name": "YouTube Music",
        "url": "https://music.youtube.com",
        "cost": "FREE (via existing YouTube channel)",
        "reaches": ["YouTube Music", "YouTube"],
        "setup_steps": [
            "1. Ensure YouTube channel has Official Artist Channel (OAC) or use topic channel",
            "2. Upload music video or audio-only with static image to YouTube",
            "3. YouTube Music auto-indexes music uploads from YouTube",
            "4. Alternative: use Amuse distribution to get on YouTube Music officially",
            "5. For OAC: need distributor (Amuse) to claim channel through YouTube's system",
            "6. Add proper metadata: music category, genre, song title in standard format",
        ],
        "requirements": {
            "audio_format": "Upload as video (MP4 with audio, or audio + cover image)",
            "cover_art": "YouTube thumbnail 1280x720 px minimum",
            "metadata": "Title: 'Artist - Song Title', description with lyrics/credits",
            "channel": "YouTube channel in good standing",
        },
        "revenue_split": "YouTube Partner Program: ~$1-3 per 1,000 views (varies)",
        "ai_music_policy": "Allowed with disclosure — YouTube requires AI-generated content labels",
        "notes": (
            "We already have YouTube channels. Upload audio with visualizer/cover art. "
            "YouTube Music picks it up automatically. For official artist channel, "
            "need to go through a distributor like Amuse. Revenue from ads. "
            "Great synergy with Ghost in the Machine anime content."
        ),
        "setup_status": "not_started",
    },
    "amazon_music": {
        "name": "Amazon Music",
        "url": "https://music.amazon.com",
        "cost": "FREE via Amuse distribution",
        "reaches": ["Amazon Music", "Amazon Music Unlimited", "Alexa"],
        "setup_steps": [
            "1. Distribute through Amuse (included in free tier)",
            "2. Amazon for Artists: claim profile at artists.amazon.com",
            "3. Customize artist page, add bio and images",
            "4. Monitor streams and playlist placements",
        ],
        "requirements": {
            "audio_format": "Handled by distributor (Amuse)",
            "cover_art": "Handled by distributor (3000x3000 via Amuse)",
            "metadata": "Handled by distributor",
            "access": "Via Amuse free tier",
        },
        "revenue_split": "~$0.004-0.005 per stream (varies). Amuse takes 20% of that.",
        "ai_music_policy": "Allowed via distributor — Amazon has not banned AI music",
        "notes": (
            "Accessible through Amuse at no extra cost. Smaller market share than "
            "Spotify/Apple but growing. Alexa integration means voice-requested plays. "
            "Good passive income stream."
        ),
        "setup_status": "not_started",
    },
    "spotify": {
        "name": "Spotify",
        "url": "https://open.spotify.com",
        "cost": "FREE via Amuse distribution",
        "reaches": ["Spotify"],
        "setup_steps": [
            "1. Distribute through Amuse (included in free tier)",
            "2. Claim Spotify for Artists profile at artists.spotify.com",
            "3. After first release, verify artist profile",
            "4. Customize profile: bio, images, artist pick, canvas videos",
            "5. Use Spotify for Artists to pitch to playlist editors (submit 7+ days before release)",
            "6. Share pre-save links for upcoming releases",
        ],
        "requirements": {
            "audio_format": "Handled by distributor (Amuse)",
            "cover_art": "Handled by distributor (3000x3000 via Amuse)",
            "metadata": "Handled by distributor. Genre selection critical for algorithmic playlists.",
            "access": "Via Amuse free tier",
        },
        "revenue_split": "~$0.003-0.005 per stream. Amuse takes 20% of royalties on free tier.",
        "ai_music_policy": (
            "Allowed with caveats — Spotify removed some AI music in 2023 but has since "
            "allowed AI-assisted music. Key: human must be involved in creative process. "
            "AI as a tool = OK. Pure bot-farm spam = not OK."
        ),
        "notes": (
            "Largest streaming platform. Algorithmic playlists (Discover Weekly, Release Radar) "
            "are key for organic growth. Submit to playlist editors 7+ days before release. "
            "Focus on consistent releases (every 2-4 weeks) to stay in algorithm. "
            "Lo-fi, ambient, and synthwave perform well on Spotify."
        ),
        "setup_status": "not_started",
    },
    "apple_music": {
        "name": "Apple Music",
        "url": "https://music.apple.com",
        "cost": "FREE via Amuse distribution",
        "reaches": ["Apple Music", "iTunes Store", "Shazam"],
        "setup_steps": [
            "1. Distribute through Amuse (included in free tier)",
            "2. Claim Apple Music for Artists profile at artists.apple.com",
            "3. After first release, verify artist identity",
            "4. Customize profile with bio and images",
            "5. Monitor analytics through Apple Music for Artists dashboard",
        ],
        "requirements": {
            "audio_format": "Handled by distributor (Amuse)",
            "cover_art": "Handled by distributor (3000x3000 via Amuse)",
            "metadata": "Handled by distributor",
            "access": "Via Amuse free tier",
        },
        "revenue_split": "~$0.007-0.01 per stream (higher than Spotify). Amuse takes 20%.",
        "ai_music_policy": "Allowed via distributor — Apple has accepted AI-generated music",
        "notes": (
            "Higher per-stream rate than Spotify. Smaller user base but more premium. "
            "Apple Music pays roughly 2x what Spotify pays per stream. "
            "Shazam integration is valuable — if someone Shazams your music in a video, "
            "it links to Apple Music. iTunes Store also allows single-track purchases."
        ),
        "setup_status": "not_started",
    },
}

# Distribution service comparison (for strategy endpoint)
DISTRIBUTORS = {
    "amuse": {
        "name": "Amuse",
        "cost": "FREE (basic) / $5.99/mo (Pro) / $29.99/yr (Plus)",
        "royalty_split": "80% artist (free) / 100% artist (Pro/Plus)",
        "stores": "50+ including Spotify, Apple Music, Amazon, TikTok, Deezer",
        "review_time": "1-3 weeks (free) / days (Pro)",
        "isrc": "Auto-generated free",
        "upc": "Auto-generated free",
        "recommendation": "START HERE — best free option",
    },
    "distrokid": {
        "name": "DistroKid",
        "cost": "$22.99/yr (Musician) / $35.99/yr (Musician Plus)",
        "royalty_split": "100% artist",
        "stores": "150+ stores",
        "review_time": "1-2 days",
        "isrc": "Auto-generated",
        "upc": "Auto-generated",
        "recommendation": "Upgrade when revenue covers cost — fastest distribution",
    },
    "tunecore": {
        "name": "TuneCore",
        "cost": "$9.99/single, $29.99/album + $49.99/yr renewal",
        "royalty_split": "100% artist",
        "stores": "150+ stores",
        "review_time": "1-3 days",
        "isrc": "Auto-generated",
        "upc": "Auto-generated",
        "recommendation": "Skip — per-release fee model bad for frequent releases",
    },
    "routenote": {
        "name": "RouteNote",
        "cost": "FREE (basic) / $9.99/yr (Premium)",
        "royalty_split": "85% artist (free) / 100% artist (Premium)",
        "stores": "25+ stores",
        "review_time": "2-5 days",
        "isrc": "Auto-generated",
        "upc": "Auto-generated",
        "recommendation": "Alternative free option if Amuse has issues",
    },
}

# ==========================================================================
# LOGGING
# ==========================================================================
LOG_FMT = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
logging.basicConfig(level=logging.INFO, format=LOG_FMT)
log = logging.getLogger("music-distributor")

# ==========================================================================
# DATABASE
# ==========================================================================

def init_db():
    """Create tables if they don't exist."""
    Path(DB_PATH).parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(DB_PATH)
    con.executescript("""
        CREATE TABLE IF NOT EXISTS tracks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            studio_track_id TEXT UNIQUE,
            title TEXT NOT NULL,
            artist_key TEXT NOT NULL DEFAULT 'hive_dynamics',
            artist_name TEXT NOT NULL DEFAULT 'Hive Dynamics',
            genre TEXT DEFAULT 'Electronic',
            subgenre TEXT DEFAULT '',
            bpm REAL DEFAULT 0,
            duration_seconds REAL DEFAULT 0,
            key_signature TEXT DEFAULT '',
            mood TEXT DEFAULT '',
            description TEXT DEFAULT '',
            file_path TEXT DEFAULT '',
            cover_art_path TEXT DEFAULT '',
            cover_art_prompt TEXT DEFAULT '',
            isrc TEXT DEFAULT '',
            upc TEXT DEFAULT '',
            lyrics TEXT DEFAULT '',
            credits TEXT DEFAULT '',
            tags TEXT DEFAULT '[]',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            status TEXT DEFAULT 'new'
        );

        CREATE TABLE IF NOT EXISTS distribution_queue (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            track_id INTEGER NOT NULL,
            platform TEXT NOT NULL,
            status TEXT DEFAULT 'pending',
            submitted_at TEXT,
            live_at TEXT,
            url TEXT DEFAULT '',
            notes TEXT DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (track_id) REFERENCES tracks(id),
            UNIQUE(track_id, platform)
        );

        CREATE TABLE IF NOT EXISTS revenue (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            track_id INTEGER NOT NULL,
            platform TEXT NOT NULL,
            period TEXT NOT NULL,
            streams INTEGER DEFAULT 0,
            revenue_usd REAL DEFAULT 0.0,
            currency TEXT DEFAULT 'USD',
            notes TEXT DEFAULT '',
            recorded_at TEXT NOT NULL,
            FOREIGN KEY (track_id) REFERENCES tracks(id)
        );

        CREATE TABLE IF NOT EXISTS platform_accounts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT UNIQUE NOT NULL,
            artist_key TEXT NOT NULL DEFAULT 'hive_dynamics',
            account_email TEXT DEFAULT '',
            profile_url TEXT DEFAULT '',
            setup_status TEXT DEFAULT 'not_started',
            verified INTEGER DEFAULT 0,
            notes TEXT DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS releases (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            artist_key TEXT NOT NULL DEFAULT 'hive_dynamics',
            release_type TEXT DEFAULT 'single',
            upc TEXT DEFAULT '',
            release_date TEXT DEFAULT '',
            cover_art_path TEXT DEFAULT '',
            cover_art_prompt TEXT DEFAULT '',
            track_ids TEXT DEFAULT '[]',
            platforms TEXT DEFAULT '[]',
            status TEXT DEFAULT 'draft',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_tracks_status ON tracks(status);
        CREATE INDEX IF NOT EXISTS idx_queue_status ON distribution_queue(status);
        CREATE INDEX IF NOT EXISTS idx_queue_platform ON distribution_queue(platform);
        CREATE INDEX IF NOT EXISTS idx_revenue_track ON revenue(track_id);
        CREATE INDEX IF NOT EXISTS idx_revenue_platform ON revenue(platform);
    """)
    con.close()
    log.info("Database initialized: %s", DB_PATH)


def get_db():
    """Get a database connection with row factory."""
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA journal_mode=WAL")
    con.execute("PRAGMA foreign_keys=ON")
    return con


# ==========================================================================
# METADATA GENERATION
# ==========================================================================

def generate_isrc(country: str = "US", registrant: str = "HV1", year: int = None,
                  sequence: int = None) -> str:
    """
    Generate an ISRC (International Standard Recording Code).
    Format: CC-XXX-YY-NNNNN
      CC = country code (2 letters)
      XXX = registrant code (3 alphanumeric)
      YY = year (2 digits)
      NNNNN = designation code (5 digits)

    Note: Real ISRCs require registration with a national ISRC agency.
    Amuse/DistroKid auto-generate real ones. This generates placeholder format.
    """
    if year is None:
        year = datetime.now(timezone.utc).year % 100
    if sequence is None:
        sequence = random.randint(10000, 99999)
    return f"{country}{registrant}{year:02d}{sequence:05d}"


def generate_upc(prefix: str = "019529") -> str:
    """
    Generate a UPC-A barcode (12 digits).
    Format: PPPPPP-IIIII-C
      PPPPPP = company prefix (6 digits)
      IIIII = item number (5 digits)
      C = check digit

    Note: Real UPCs require GS1 registration ($250+/yr).
    Distributors (Amuse) auto-generate them for free.
    This generates placeholder format for tracking.
    """
    item = random.randint(10000, 99999)
    base = f"{prefix}{item}"
    # Calculate UPC check digit
    odd_sum = sum(int(base[i]) for i in range(0, 11, 2))
    even_sum = sum(int(base[i]) for i in range(1, 11, 2))
    check = (10 - ((odd_sum * 3 + even_sum) % 10)) % 10
    return f"{base}{check}"


def generate_cover_art_prompt(track_title: str, genre: str, mood: str,
                               artist_key: str = "hive_dynamics") -> str:
    """Generate an SDXL-optimized prompt for cover art."""
    style_map = {
        "hive_dynamics": {
            "base": "album cover art, modern electronic music",
            "styles": [
                "abstract digital art, neon gradients, geometric shapes",
                "minimalist design, bold typography, dark background",
                "futuristic cityscape, cyberpunk aesthetic, glowing lights",
                "abstract sound waves visualization, deep colors",
                "nature meets technology, organic circuits, bioluminescent",
            ],
        },
        "ghost_machine": {
            "base": "anime album cover art, japanese animation style",
            "styles": [
                "cyberpunk city at night, neon signs in Japanese, rain reflections",
                "anime character silhouette against digital matrix, blue glow",
                "japanese temple with holographic projections, cherry blossoms",
                "mecha and nature fusion, overgrown circuits, sunset",
                "abstract AI visualization, neural network patterns, anime aesthetic",
            ],
        },
    }

    artist_style = style_map.get(artist_key, style_map["hive_dynamics"])
    style = random.choice(artist_style["styles"])

    mood_colors = {
        "energetic": "vibrant reds and oranges, dynamic composition",
        "chill": "cool blues and purples, calm flowing shapes",
        "dark": "deep blacks and dark purples, ominous atmosphere",
        "uplifting": "warm yellows and golds, light rays, hopeful",
        "melancholic": "muted blues and grays, rain, solitary figure",
        "intense": "high contrast, sharp angles, electric energy",
        "dreamy": "soft pastels, ethereal glow, floating elements",
        "mysterious": "deep shadows, faint glowing symbols, fog",
    }
    mood_desc = mood_colors.get(mood.lower(), "atmospheric, professional")

    return (
        f"{artist_style['base']}, {style}, {mood_desc}, "
        f"inspired by '{track_title}', {genre} music, "
        f"high quality, 4k, detailed, professional album artwork, "
        f"no text, no watermark, square format"
    )


def generate_track_tags(genre: str, subgenre: str, mood: str,
                        artist_key: str) -> List[str]:
    """Generate platform-appropriate tags for a track."""
    base_tags = [genre.lower()]
    if subgenre:
        base_tags.append(subgenre.lower())
    if mood:
        base_tags.append(mood.lower())

    artist_info = ARTISTS.get(artist_key, ARTISTS["hive_dynamics"])
    base_tags.extend([g.lower() for g in artist_info["genres"][:3]])

    extra_tags = [
        "ai music", "ai generated", "neural network music",
        "electronic", "instrumental",
    ]
    if artist_key == "ghost_machine":
        extra_tags.extend(["anime", "anime ost", "japanese electronic",
                           "ghost in the machine"])
    else:
        extra_tags.extend(["hive dynamics", "ai beats", "computer generated"])

    all_tags = list(dict.fromkeys(base_tags + extra_tags))  # dedupe, preserve order
    return all_tags[:15]  # Most platforms cap at 10-15 tags


# ==========================================================================
# STUDIO SYNC — pull tracks from music studio (port 8911)
# ==========================================================================

async def sync_from_studio():
    """Pull latest tracks from the music studio service."""
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.get(f"{STUDIO_URL}/api/tracks")
            if resp.status_code != 200:
                log.warning("Studio sync failed: HTTP %d", resp.status_code)
                return 0

            data = resp.json()
            tracks = data if isinstance(data, list) else data.get("tracks", [])

            con = get_db()
            imported = 0
            now = datetime.now(timezone.utc).isoformat()

            for t in tracks:
                track_id = str(t.get("id", t.get("track_id", "")))
                if not track_id:
                    continue

                # Check if already imported
                existing = con.execute(
                    "SELECT id FROM tracks WHERE studio_track_id = ?",
                    (track_id,)
                ).fetchone()
                if existing:
                    continue

                title = t.get("title", f"Untitled-{track_id}")
                genre = t.get("genre", "Electronic")
                mood = t.get("mood", "")
                artist_key = t.get("artist_key", "hive_dynamics")
                artist_name = ARTISTS.get(artist_key, ARTISTS["hive_dynamics"])["name"]

                # Generate metadata
                isrc = generate_isrc()
                upc = generate_upc()
                tags = generate_track_tags(genre, t.get("subgenre", ""), mood, artist_key)
                cover_prompt = generate_cover_art_prompt(title, genre, mood, artist_key)

                con.execute("""
                    INSERT INTO tracks (
                        studio_track_id, title, artist_key, artist_name,
                        genre, subgenre, bpm, duration_seconds,
                        key_signature, mood, description, file_path,
                        cover_art_prompt, isrc, upc, tags,
                        created_at, updated_at, status
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'new')
                """, (
                    track_id, title, artist_key, artist_name,
                    genre, t.get("subgenre", ""), t.get("bpm", 0),
                    t.get("duration_seconds", t.get("duration", 0)),
                    t.get("key_signature", t.get("key", "")),
                    mood, t.get("description", ""), t.get("file_path", ""),
                    cover_prompt, isrc, upc, json.dumps(tags),
                    now, now,
                ))
                imported += 1

            con.commit()
            con.close()
            if imported:
                log.info("Imported %d new tracks from studio", imported)
            return imported

    except httpx.ConnectError:
        log.debug("Studio not reachable at %s — will retry", STUDIO_URL)
        return 0
    except Exception as e:
        log.warning("Studio sync error: %s", e)
        return 0


# ==========================================================================
# BACKGROUND TASKS
# ==========================================================================

async def sync_loop():
    """Periodically sync tracks from studio."""
    while True:
        try:
            await sync_from_studio()
        except Exception as e:
            log.error("Sync loop error: %s", e)
        await asyncio.sleep(SYNC_INTERVAL)


# ==========================================================================
# STRATEGY ENGINE
# ==========================================================================

def get_distribution_strategy() -> Dict[str, Any]:
    """Return comprehensive music distribution strategy."""
    return {
        "last_updated": "2026-03-23",
        "overview": (
            "AI-generated music can be distributed on all major platforms. "
            "The strategy is: produce consistently, distribute everywhere free, "
            "build audience on SoundCloud/Bandcamp/YouTube, then leverage Spotify "
            "algorithmic playlists for passive income."
        ),
        "distribution_plan": {
            "phase_1_immediate": {
                "name": "Foundation (Week 1-2)",
                "actions": [
                    "Sign up for Amuse (FREE) — distributes to Spotify, Apple Music, Amazon, 50+ stores",
                    "Create SoundCloud account — upload ALL tracks immediately (free, instant)",
                    "Create Bandcamp page — upload tracks with 'name your price' ($0 minimum)",
                    "Upload to YouTube as audio visualizer videos (free, instant)",
                    "Set up artist profiles on Spotify for Artists and Apple Music for Artists",
                ],
                "cost": "$0",
                "timeline": "1-2 weeks for Amuse approval, instant for SoundCloud/Bandcamp/YouTube",
            },
            "phase_2_growth": {
                "name": "Consistent Releases (Month 1-3)",
                "actions": [
                    "Release new single every 2 weeks (Spotify algorithm loves consistency)",
                    "Submit to Spotify playlist editors 7+ days before each release",
                    "Cross-promote: SoundCloud -> YouTube -> Spotify pre-save links",
                    "Create 15-30 second clips for TikTok/Instagram Reels",
                    "Engage SoundCloud community (comment, repost, collaborate)",
                    "Run Bandcamp Friday promotions (first Friday of month)",
                ],
                "cost": "$0",
                "timeline": "Ongoing",
            },
            "phase_3_monetization": {
                "name": "Revenue Optimization (Month 3-6)",
                "actions": [
                    "Upgrade to Amuse Pro ($5.99/mo) when streams cover cost — get 100% royalties",
                    "Apply for SoundCloud Premier (requires 1K plays/month)",
                    "Set Bandcamp prices ($1-5 per track, $5-15 per album)",
                    "YouTube Partner Program monetization",
                    "Consider DistroKid ($22.99/yr) for faster distribution + unlimited uploads",
                    "Submit to independent playlist curators (SubmitHub, PlaylistPush — some free)",
                ],
                "cost": "$5.99-$22.99/month",
                "timeline": "Month 3+",
            },
        },
        "genre_trends_2026": {
            "hot_genres": [
                {"genre": "Lo-Fi Hip Hop / Chillhop", "growth": "strong",
                 "notes": "Study/work playlists have billions of streams. Low competition per track, high volume."},
                {"genre": "Synthwave / Retrowave", "growth": "strong",
                 "notes": "Nostalgic 80s sound. Great for anime/cyberpunk aesthetics. Passionate niche community."},
                {"genre": "Ambient / Meditation", "growth": "very strong",
                 "notes": "Wellness market drives streams. Long tracks = more stream revenue per listen."},
                {"genre": "AI Music / Experimental Electronic", "growth": "emerging",
                 "notes": "Novelty factor + tech audience. Good for content creators seeking royalty-free music."},
                {"genre": "Anime OST / J-Electronic", "growth": "strong",
                 "notes": "Anime audience is massive and passionate. Ghost Machine brand fits perfectly."},
                {"genre": "Dark Ambient / Cyberpunk", "growth": "moderate",
                 "notes": "Niche but dedicated audience. Popular for gaming, coding, and RPG background music."},
            ],
            "recommendation": (
                "Focus on lo-fi hip hop and ambient for Hive Dynamics (high stream volume), "
                "and anime OST / synthwave for Ghost Machine (passionate niche). "
                "Both artists should produce 10-30 minute ambient 'mixes' for study/work "
                "playlists — these get looped and generate more streams per listener."
            ),
        },
        "release_schedule": {
            "frequency": "1 single every 2 weeks, 1 EP (4-6 tracks) monthly",
            "best_release_day": "Friday (global new music day for Spotify/Apple Music)",
            "best_release_time": "00:00 UTC (midnight) — appears on New Music Friday",
            "pre_release": "Submit to Spotify editors 7-14 days before release",
            "calendar": [
                "Week 1: Produce + master track",
                "Week 2: Generate cover art, write metadata, submit to Amuse",
                "Week 3: Track goes live (Amuse review ~1-2 weeks)",
                "Week 4: Promote on SoundCloud/YouTube/social, start next track",
            ],
            "album_strategy": (
                "After 8-10 singles, compile into an album for additional streaming. "
                "Albums get playlist preference on some platforms. "
                "Ghost Machine: release anime 'seasons' as albums (Season 1 OST, etc.)"
            ),
        },
        "revenue_projections": {
            "disclaimer": "Estimates based on 2025-2026 average rates. Actual varies widely.",
            "per_stream_rates": {
                "spotify": {"low": 0.003, "avg": 0.004, "high": 0.005},
                "apple_music": {"low": 0.007, "avg": 0.008, "high": 0.01},
                "amazon_music": {"low": 0.004, "avg": 0.0045, "high": 0.005},
                "youtube_music": {"low": 0.001, "avg": 0.002, "high": 0.003},
                "soundcloud": {"low": 0.003, "avg": 0.004, "high": 0.005},
            },
            "scenarios": {
                "month_3": {
                    "total_streams": 5000,
                    "revenue_estimate": "$15-25",
                    "notes": "Initial audience building. Most streams from SoundCloud + YouTube.",
                },
                "month_6": {
                    "total_streams": 25000,
                    "revenue_estimate": "$75-125",
                    "notes": "Algorithm starts picking up consistent releases. Playlist placements help.",
                },
                "month_12": {
                    "total_streams": 100000,
                    "revenue_estimate": "$300-500",
                    "notes": "Catalog effect — old tracks keep earning. 20+ tracks compound.",
                },
                "month_24": {
                    "total_streams": 500000,
                    "revenue_estimate": "$1,500-2,500",
                    "notes": "50+ track catalog. Multiple playlist placements. Fan base established.",
                },
            },
            "bandcamp_direct_sales": {
                "notes": (
                    "Bandcamp revenue is separate from streaming. "
                    "If 5% of listeners buy at $5 avg, 1000 fans = $250/month. "
                    "True fans model: 100 true fans x $10/month = $1,000/month."
                ),
            },
            "maximizing_revenue": [
                "Long tracks (3+ minutes) count as full streams on Spotify",
                "Ambient/lo-fi 'mixes' (10-30 min) get looped = more streams per listener",
                "Release consistently — algorithm rewards frequency",
                "Cross-promote across platforms (different audiences on each)",
                "Engage playlist curators — personal outreach > submission tools",
                "Bandcamp for superfans — higher per-sale revenue than any streaming",
                "License tracks for content creators (Epidemic Sound, Artlist model)",
                "Offer stems/loops for producers (extra revenue from same music)",
            ],
        },
        "free_distribution_services": {
            "recommended": [
                {
                    "name": "Amuse",
                    "cost": "FREE",
                    "pros": "No cost, 50+ stores, auto ISRC/UPC, decent review time",
                    "cons": "20% royalty cut on free tier, 1-3 week review",
                    "verdict": "USE THIS — best free option for major platforms",
                },
                {
                    "name": "RouteNote",
                    "cost": "FREE",
                    "pros": "No cost, 25+ stores, no release limits",
                    "cons": "15% royalty cut on free tier, fewer stores than Amuse",
                    "verdict": "Good backup if Amuse has issues",
                },
                {
                    "name": "SoundCloud (direct)",
                    "cost": "FREE",
                    "pros": "Instant upload, community features, embeddable player",
                    "cons": "3-hour limit on free, no monetization until Premier",
                    "verdict": "USE THIS — best for immediate audience + discovery",
                },
                {
                    "name": "Bandcamp (direct)",
                    "cost": "FREE",
                    "pros": "Fan-direct sales, highest revenue per sale, community",
                    "cons": "15% cut on sales, smaller audience than Spotify",
                    "verdict": "USE THIS — best for direct fan revenue",
                },
                {
                    "name": "YouTube (direct)",
                    "cost": "FREE",
                    "pros": "Massive audience, video synergy, ad revenue",
                    "cons": "Requires video format, lower per-play rate",
                    "verdict": "USE THIS — we already have channels",
                },
            ],
            "paid_when_ready": [
                {
                    "name": "DistroKid",
                    "cost": "$22.99/yr",
                    "pros": "Fastest distribution, unlimited uploads, 100% royalties",
                    "cons": "Annual fee, music removed if you stop paying",
                    "verdict": "Upgrade when revenue covers cost (~$2/month in streams)",
                },
                {
                    "name": "Amuse Pro",
                    "cost": "$5.99/mo",
                    "pros": "100% royalties, faster review, same platform",
                    "verdict": "Upgrade from free Amuse when streams generate $6+/month",
                },
            ],
        },
    }


# ==========================================================================
# FASTAPI APP
# ==========================================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown."""
    init_db()
    _seed_platform_accounts()
    log.info("Music Distributor starting on port %d", PORT)
    task = asyncio.create_task(sync_loop())
    yield
    task.cancel()
    log.info("Music Distributor shutting down")


app = FastAPI(
    title="Hive Music Distributor",
    description="Manages music distribution to streaming platforms",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def _seed_platform_accounts():
    """Seed platform_accounts table with known platforms."""
    con = get_db()
    now = datetime.now(timezone.utc).isoformat()
    for key, plat in PLATFORMS.items():
        existing = con.execute(
            "SELECT id FROM platform_accounts WHERE platform = ?", (key,)
        ).fetchone()
        if not existing:
            con.execute("""
                INSERT INTO platform_accounts (platform, setup_status, created_at, updated_at)
                VALUES (?, 'not_started', ?, ?)
            """, (key, now, now))
    con.commit()
    con.close()


# --------------------------------------------------------------------------
# Pydantic models
# --------------------------------------------------------------------------

class TrackCreate(BaseModel):
    title: str
    artist_key: str = "hive_dynamics"
    genre: str = "Electronic"
    subgenre: str = ""
    bpm: float = 0
    duration_seconds: float = 0
    key_signature: str = ""
    mood: str = ""
    description: str = ""
    file_path: str = ""
    lyrics: str = ""
    credits: str = ""


class DistributeRequest(BaseModel):
    platforms: List[str] = []  # empty = all platforms
    release_date: str = ""  # YYYY-MM-DD, empty = ASAP
    notes: str = ""


class PlatformUpdate(BaseModel):
    setup_status: str = ""
    account_email: str = ""
    profile_url: str = ""
    notes: str = ""


class RevenueEntry(BaseModel):
    track_id: int
    platform: str
    period: str  # e.g. "2026-03"
    streams: int = 0
    revenue_usd: float = 0.0
    notes: str = ""


# --------------------------------------------------------------------------
# ENDPOINTS
# --------------------------------------------------------------------------

@app.get("/health")
async def health():
    """Health check."""
    con = get_db()
    track_count = con.execute("SELECT COUNT(*) FROM tracks").fetchone()[0]
    queue_count = con.execute(
        "SELECT COUNT(*) FROM distribution_queue WHERE status = 'pending'"
    ).fetchone()[0]
    distributed = con.execute(
        "SELECT COUNT(*) FROM distribution_queue WHERE status = 'live'"
    ).fetchone()[0]
    con.close()
    return {
        "status": "healthy",
        "service": "music-distributor",
        "port": PORT,
        "tracks": track_count,
        "pending_distribution": queue_count,
        "live_on_platforms": distributed,
        "studio_url": STUDIO_URL,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


@app.get("/api/platforms")
async def list_platforms():
    """List all platforms with setup status and detailed info."""
    con = get_db()
    accounts = {
        row["platform"]: dict(row)
        for row in con.execute("SELECT * FROM platform_accounts").fetchall()
    }
    con.close()

    result = []
    for key, plat in PLATFORMS.items():
        acct = accounts.get(key, {})
        entry = {
            "key": key,
            "name": plat["name"],
            "url": plat["url"],
            "cost": plat["cost"],
            "reaches": plat["reaches"],
            "setup_status": acct.get("setup_status", "not_started"),
            "account_email": acct.get("account_email", ""),
            "profile_url": acct.get("profile_url", ""),
            "verified": bool(acct.get("verified", 0)),
            "setup_steps": plat["setup_steps"],
            "requirements": plat["requirements"],
            "revenue_split": plat["revenue_split"],
            "ai_music_policy": plat["ai_music_policy"],
            "notes": plat["notes"],
        }
        result.append(entry)

    return {
        "platforms": result,
        "total": len(result),
        "distributors": DISTRIBUTORS,
    }


@app.put("/api/platforms/{platform_key}")
async def update_platform(platform_key: str, update: PlatformUpdate):
    """Update platform account info (setup status, email, URL)."""
    if platform_key not in PLATFORMS:
        raise HTTPException(404, f"Unknown platform: {platform_key}")

    con = get_db()
    now = datetime.now(timezone.utc).isoformat()

    sets = []
    vals = []
    if update.setup_status:
        sets.append("setup_status = ?")
        vals.append(update.setup_status)
    if update.account_email:
        sets.append("account_email = ?")
        vals.append(update.account_email)
    if update.profile_url:
        sets.append("profile_url = ?")
        vals.append(update.profile_url)
    if update.notes:
        sets.append("notes = ?")
        vals.append(update.notes)

    if not sets:
        raise HTTPException(400, "No fields to update")

    sets.append("updated_at = ?")
    vals.append(now)
    vals.append(platform_key)

    con.execute(
        f"UPDATE platform_accounts SET {', '.join(sets)} WHERE platform = ?",
        vals,
    )
    con.commit()
    con.close()
    return {"status": "updated", "platform": platform_key}


@app.get("/api/tracks")
async def list_tracks(status: Optional[str] = None, artist: Optional[str] = None):
    """List all tracked music."""
    con = get_db()
    query = "SELECT * FROM tracks WHERE 1=1"
    params = []
    if status:
        query += " AND status = ?"
        params.append(status)
    if artist:
        query += " AND artist_key = ?"
        params.append(artist)
    query += " ORDER BY created_at DESC"

    rows = con.execute(query, params).fetchall()
    con.close()

    tracks = []
    for r in rows:
        t = dict(r)
        try:
            t["tags"] = json.loads(t.get("tags", "[]"))
        except (json.JSONDecodeError, TypeError):
            t["tags"] = []
        tracks.append(t)

    return {"tracks": tracks, "total": len(tracks)}


@app.post("/api/tracks")
async def create_track(track: TrackCreate):
    """Manually add a track (in addition to studio sync)."""
    con = get_db()
    now = datetime.now(timezone.utc).isoformat()

    artist_name = ARTISTS.get(track.artist_key, ARTISTS["hive_dynamics"])["name"]
    isrc = generate_isrc()
    upc = generate_upc()
    tags = generate_track_tags(track.genre, track.subgenre, track.mood, track.artist_key)
    cover_prompt = generate_cover_art_prompt(
        track.title, track.genre, track.mood, track.artist_key
    )

    # Generate a studio_track_id for manually added tracks
    studio_id = f"manual-{hashlib.md5(f'{track.title}{now}'.encode()).hexdigest()[:12]}"

    cur = con.execute("""
        INSERT INTO tracks (
            studio_track_id, title, artist_key, artist_name,
            genre, subgenre, bpm, duration_seconds,
            key_signature, mood, description, file_path,
            cover_art_prompt, isrc, upc, tags,
            lyrics, credits, created_at, updated_at, status
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'new')
    """, (
        studio_id, track.title, track.artist_key, artist_name,
        track.genre, track.subgenre, track.bpm, track.duration_seconds,
        track.key_signature, track.mood, track.description, track.file_path,
        cover_prompt, isrc, upc, json.dumps(tags),
        track.lyrics, track.credits, now, now,
    ))
    track_id = cur.lastrowid
    con.commit()
    con.close()

    return {
        "status": "created",
        "track_id": track_id,
        "isrc": isrc,
        "upc": upc,
        "cover_art_prompt": cover_prompt,
        "tags": tags,
    }


@app.get("/api/tracks/{track_id}")
async def get_track(track_id: int):
    """Get full track details with distribution status."""
    con = get_db()
    track = con.execute("SELECT * FROM tracks WHERE id = ?", (track_id,)).fetchone()
    if not track:
        con.close()
        raise HTTPException(404, f"Track {track_id} not found")

    t = dict(track)
    try:
        t["tags"] = json.loads(t.get("tags", "[]"))
    except (json.JSONDecodeError, TypeError):
        t["tags"] = []

    # Get distribution status
    dist_rows = con.execute(
        "SELECT * FROM distribution_queue WHERE track_id = ? ORDER BY platform",
        (track_id,)
    ).fetchall()
    t["distribution"] = [dict(d) for d in dist_rows]

    # Get revenue
    rev_rows = con.execute(
        "SELECT * FROM revenue WHERE track_id = ? ORDER BY period DESC",
        (track_id,)
    ).fetchall()
    t["revenue"] = [dict(r) for r in rev_rows]

    con.close()
    return t


@app.get("/api/queue")
async def get_queue(status: Optional[str] = Query(None)):
    """Get distribution queue — tracks pending or in-progress."""
    con = get_db()
    if status:
        rows = con.execute("""
            SELECT dq.*, t.title, t.artist_name, t.genre
            FROM distribution_queue dq
            JOIN tracks t ON t.id = dq.track_id
            WHERE dq.status = ?
            ORDER BY dq.created_at DESC
        """, (status,)).fetchall()
    else:
        rows = con.execute("""
            SELECT dq.*, t.title, t.artist_name, t.genre
            FROM distribution_queue dq
            JOIN tracks t ON t.id = dq.track_id
            WHERE dq.status IN ('pending', 'submitted', 'in_review')
            ORDER BY dq.created_at DESC
        """).fetchall()
    con.close()

    return {
        "queue": [dict(r) for r in rows],
        "total": len(rows),
    }


@app.get("/api/distributed")
async def get_distributed():
    """Get tracks that are live on platforms."""
    con = get_db()
    rows = con.execute("""
        SELECT dq.*, t.title, t.artist_name, t.genre, t.isrc, t.upc
        FROM distribution_queue dq
        JOIN tracks t ON t.id = dq.track_id
        WHERE dq.status = 'live'
        ORDER BY dq.live_at DESC
    """).fetchall()
    con.close()

    return {
        "distributed": [dict(r) for r in rows],
        "total": len(rows),
    }


@app.post("/api/distribute/{track_id}")
async def distribute_track(track_id: int, req: Optional[DistributeRequest] = None):
    """
    Mark a track for distribution to platforms.
    If no platforms specified, queues for ALL platforms.
    """
    con = get_db()
    track = con.execute("SELECT * FROM tracks WHERE id = ?", (track_id,)).fetchone()
    if not track:
        con.close()
        raise HTTPException(404, f"Track {track_id} not found")

    now = datetime.now(timezone.utc).isoformat()
    platforms = (req.platforms if req and req.platforms else list(PLATFORMS.keys()))
    notes = req.notes if req else ""

    queued = []
    skipped = []
    for plat in platforms:
        if plat not in PLATFORMS:
            skipped.append({"platform": plat, "reason": "unknown platform"})
            continue

        # Check if already queued
        existing = con.execute(
            "SELECT id, status FROM distribution_queue WHERE track_id = ? AND platform = ?",
            (track_id, plat)
        ).fetchone()
        if existing:
            skipped.append({"platform": plat, "reason": f"already {existing['status']}"})
            continue

        con.execute("""
            INSERT INTO distribution_queue (
                track_id, platform, status, notes, created_at, updated_at
            ) VALUES (?, ?, 'pending', ?, ?, ?)
        """, (track_id, plat, notes, now, now))
        queued.append(plat)

    # Update track status
    con.execute(
        "UPDATE tracks SET status = 'queued', updated_at = ? WHERE id = ?",
        (now, track_id)
    )
    con.commit()
    con.close()

    return {
        "status": "queued",
        "track_id": track_id,
        "track_title": track["title"],
        "queued_platforms": queued,
        "skipped": skipped,
        "next_steps": [
            f"Upload to {p}: see GET /api/platforms for setup steps" for p in queued
        ],
    }


@app.put("/api/queue/{queue_id}")
async def update_queue_item(queue_id: int, status: str = Query(...),
                             url: str = "", notes: str = ""):
    """Update distribution queue item status (pending -> submitted -> in_review -> live | failed)."""
    valid_statuses = ["pending", "submitted", "in_review", "live", "failed", "removed"]
    if status not in valid_statuses:
        raise HTTPException(400, f"Invalid status. Must be one of: {valid_statuses}")

    con = get_db()
    now = datetime.now(timezone.utc).isoformat()

    item = con.execute("SELECT * FROM distribution_queue WHERE id = ?", (queue_id,)).fetchone()
    if not item:
        con.close()
        raise HTTPException(404, f"Queue item {queue_id} not found")

    updates = {"status": status, "updated_at": now}
    if status == "submitted":
        updates["submitted_at"] = now
    if status == "live":
        updates["live_at"] = now
    if url:
        updates["url"] = url
    if notes:
        updates["notes"] = notes

    set_clause = ", ".join(f"{k} = ?" for k in updates)
    vals = list(updates.values()) + [queue_id]
    con.execute(f"UPDATE distribution_queue SET {set_clause} WHERE id = ?", vals)

    # If all platforms are live, update track status
    if status == "live":
        track_id = item["track_id"]
        pending = con.execute(
            "SELECT COUNT(*) FROM distribution_queue WHERE track_id = ? AND status != 'live'",
            (track_id,)
        ).fetchone()[0]
        if pending == 0:
            con.execute(
                "UPDATE tracks SET status = 'distributed', updated_at = ? WHERE id = ?",
                (now, track_id)
            )

    con.commit()
    con.close()
    return {"status": "updated", "queue_id": queue_id, "new_status": status}


@app.get("/api/revenue")
async def get_revenue(
    platform: Optional[str] = None,
    period: Optional[str] = None,
    track_id: Optional[int] = None,
):
    """Get revenue data across platforms."""
    con = get_db()

    # Per-platform summary
    platform_summary = {}
    for key in PLATFORMS:
        row = con.execute("""
            SELECT
                COALESCE(SUM(streams), 0) as total_streams,
                COALESCE(SUM(revenue_usd), 0) as total_revenue
            FROM revenue WHERE platform = ?
        """, (key,)).fetchone()
        platform_summary[key] = {
            "platform": PLATFORMS[key]["name"],
            "total_streams": row[0],
            "total_revenue_usd": round(row[1], 2),
        }

    # Overall totals
    overall = con.execute("""
        SELECT
            COALESCE(SUM(streams), 0) as total_streams,
            COALESCE(SUM(revenue_usd), 0) as total_revenue
        FROM revenue
    """).fetchone()

    # Detailed records (filtered)
    query = "SELECT r.*, t.title, t.artist_name FROM revenue r JOIN tracks t ON t.id = r.track_id WHERE 1=1"
    params = []
    if platform:
        query += " AND r.platform = ?"
        params.append(platform)
    if period:
        query += " AND r.period = ?"
        params.append(period)
    if track_id:
        query += " AND r.track_id = ?"
        params.append(track_id)
    query += " ORDER BY r.period DESC, r.platform"
    records = [dict(r) for r in con.execute(query, params).fetchall()]

    con.close()

    return {
        "summary": {
            "total_streams": overall[0],
            "total_revenue_usd": round(overall[1], 2),
            "currency": "USD",
        },
        "by_platform": platform_summary,
        "records": records,
        "note": (
            "Revenue data is entered manually from platform dashboards until "
            "API integrations are built. Check Amuse app, Spotify for Artists, "
            "Bandcamp stats, and SoundCloud insights for latest numbers."
        ),
    }


@app.post("/api/revenue")
async def add_revenue(entry: RevenueEntry):
    """Add a revenue record (manual entry from platform dashboards)."""
    con = get_db()
    now = datetime.now(timezone.utc).isoformat()

    # Verify track exists
    track = con.execute("SELECT id FROM tracks WHERE id = ?", (entry.track_id,)).fetchone()
    if not track:
        con.close()
        raise HTTPException(404, f"Track {entry.track_id} not found")

    con.execute("""
        INSERT INTO revenue (track_id, platform, period, streams, revenue_usd, notes, recorded_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (entry.track_id, entry.platform, entry.period, entry.streams,
          entry.revenue_usd, entry.notes, now))
    con.commit()
    con.close()

    return {"status": "recorded", "track_id": entry.track_id, "platform": entry.platform}


@app.get("/api/strategy")
async def get_strategy():
    """Return comprehensive music distribution and revenue strategy."""
    return get_distribution_strategy()


@app.get("/api/artists")
async def list_artists():
    """List artist profiles with their info."""
    con = get_db()
    result = {}
    for key, artist in ARTISTS.items():
        track_count = con.execute(
            "SELECT COUNT(*) FROM tracks WHERE artist_key = ?", (key,)
        ).fetchone()[0]
        live_count = con.execute("""
            SELECT COUNT(DISTINCT dq.platform)
            FROM distribution_queue dq
            JOIN tracks t ON t.id = dq.track_id
            WHERE t.artist_key = ? AND dq.status = 'live'
        """, (key,)).fetchone()[0]

        result[key] = {
            **artist,
            "tracks": track_count,
            "live_on_platforms": live_count,
        }
    con.close()
    return {"artists": result}


@app.get("/api/metadata/{track_id}")
async def get_track_metadata(track_id: int):
    """Get complete distribution metadata for a track (ready for upload)."""
    con = get_db()
    track = con.execute("SELECT * FROM tracks WHERE id = ?", (track_id,)).fetchone()
    if not track:
        con.close()
        raise HTTPException(404, f"Track {track_id} not found")
    con.close()

    t = dict(track)
    try:
        tags = json.loads(t.get("tags", "[]"))
    except (json.JSONDecodeError, TypeError):
        tags = []

    artist = ARTISTS.get(t["artist_key"], ARTISTS["hive_dynamics"])

    return {
        "track_id": t["id"],
        "title": t["title"],
        "artist": {
            "name": t["artist_name"],
            "bio": artist["bio"],
            "genres": artist["genres"],
        },
        "metadata": {
            "isrc": t["isrc"],
            "upc": t["upc"],
            "genre": t["genre"],
            "subgenre": t["subgenre"],
            "bpm": t["bpm"],
            "duration_seconds": t["duration_seconds"],
            "key_signature": t["key_signature"],
            "mood": t["mood"],
            "tags": tags,
            "lyrics": t["lyrics"],
            "credits": t["credits"] or f"Produced by {t['artist_name']}. AI-generated music.",
            "copyright": f"(C) {datetime.now().year} {t['artist_name']}. All rights reserved.",
            "language": "en",
            "explicit": False,
        },
        "cover_art": {
            "path": t["cover_art_path"],
            "sdxl_prompt": t["cover_art_prompt"],
            "requirements": {
                "amuse": "3000x3000 px, JPEG/PNG",
                "soundcloud": "800x800 px minimum",
                "bandcamp": "1400x1400 px minimum (3000x3000 recommended)",
                "youtube": "1280x720 px minimum (thumbnail)",
            },
        },
        "platform_specific": {
            "spotify": {
                "genre_tags": artist.get("spotify_genre_tags", []),
                "submit_to_editors": True,
                "canvas_video": "Recommended: 3-8 sec looping vertical video",
            },
            "soundcloud": {
                "tags": tags[:5],  # SoundCloud allows up to 5 tags
                "description": t["description"] or f"{t['title']} by {t['artist_name']}",
                "enable_downloads": True,
                "license": "all-rights-reserved",
            },
            "bandcamp": {
                "tags": tags[:10],  # Bandcamp allows up to 10 tags
                "about": t["description"] or artist["bio"],
                "pricing": "name-your-price",
                "minimum_price": 0,
            },
            "youtube": {
                "title_format": f"{t['artist_name']} - {t['title']} [Official Audio]",
                "description_template": (
                    f"{t['title']} by {t['artist_name']}\n\n"
                    f"{t['description'] or ''}\n\n"
                    f"Genre: {t['genre']}\n"
                    f"Listen on Spotify: [link]\n"
                    f"Listen on Apple Music: [link]\n"
                    f"Buy on Bandcamp: [link]\n\n"
                    f"#{''.join(t['genre'].split())} #AIMusic #{''.join(t['artist_name'].split())}"
                ),
                "category": "Music",
                "ai_disclosure": True,
            },
        },
    }


@app.post("/api/sync")
async def trigger_sync():
    """Manually trigger sync from music studio."""
    imported = await sync_from_studio()
    return {"status": "synced", "new_tracks_imported": imported}


@app.get("/api/stats")
async def get_stats():
    """Get overall distribution statistics."""
    con = get_db()

    tracks_total = con.execute("SELECT COUNT(*) FROM tracks").fetchone()[0]
    tracks_new = con.execute("SELECT COUNT(*) FROM tracks WHERE status = 'new'").fetchone()[0]
    tracks_queued = con.execute("SELECT COUNT(*) FROM tracks WHERE status = 'queued'").fetchone()[0]
    tracks_distributed = con.execute("SELECT COUNT(*) FROM tracks WHERE status = 'distributed'").fetchone()[0]

    queue_pending = con.execute("SELECT COUNT(*) FROM distribution_queue WHERE status = 'pending'").fetchone()[0]
    queue_submitted = con.execute("SELECT COUNT(*) FROM distribution_queue WHERE status = 'submitted'").fetchone()[0]
    queue_live = con.execute("SELECT COUNT(*) FROM distribution_queue WHERE status = 'live'").fetchone()[0]

    total_streams = con.execute("SELECT COALESCE(SUM(streams), 0) FROM revenue").fetchone()[0]
    total_revenue = con.execute("SELECT COALESCE(SUM(revenue_usd), 0) FROM revenue").fetchone()[0]

    platforms_setup = con.execute(
        "SELECT COUNT(*) FROM platform_accounts WHERE setup_status != 'not_started'"
    ).fetchone()[0]

    # Per-artist breakdown
    artist_stats = {}
    for key in ARTISTS:
        count = con.execute("SELECT COUNT(*) FROM tracks WHERE artist_key = ?", (key,)).fetchone()[0]
        artist_stats[key] = {"name": ARTISTS[key]["name"], "tracks": count}

    con.close()

    return {
        "tracks": {
            "total": tracks_total,
            "new": tracks_new,
            "queued": tracks_queued,
            "distributed": tracks_distributed,
        },
        "distribution_queue": {
            "pending": queue_pending,
            "submitted": queue_submitted,
            "live": queue_live,
        },
        "revenue": {
            "total_streams": total_streams,
            "total_revenue_usd": round(total_revenue, 2),
        },
        "platforms_configured": platforms_setup,
        "total_platforms": len(PLATFORMS),
        "artists": artist_stats,
    }


@app.get("/api/releases")
async def list_releases():
    """List all releases (singles, EPs, albums)."""
    con = get_db()
    rows = con.execute("SELECT * FROM releases ORDER BY created_at DESC").fetchall()
    con.close()

    releases = []
    for r in rows:
        rel = dict(r)
        try:
            rel["track_ids"] = json.loads(rel.get("track_ids", "[]"))
            rel["platforms"] = json.loads(rel.get("platforms", "[]"))
        except (json.JSONDecodeError, TypeError):
            rel["track_ids"] = []
            rel["platforms"] = []
        releases.append(rel)

    return {"releases": releases, "total": len(releases)}


@app.post("/api/releases")
async def create_release(
    title: str = Query(...),
    artist_key: str = Query("hive_dynamics"),
    release_type: str = Query("single"),
    track_ids: str = Query("[]"),
    release_date: str = Query(""),
):
    """Create a release (single, EP, or album) grouping tracks."""
    con = get_db()
    now = datetime.now(timezone.utc).isoformat()
    upc = generate_upc()

    try:
        ids = json.loads(track_ids)
    except json.JSONDecodeError:
        ids = []

    # Generate cover art prompt for the release
    genre = ""
    if ids:
        track = con.execute("SELECT genre, mood FROM tracks WHERE id = ?", (ids[0],)).fetchone()
        if track:
            genre = track["genre"]

    cover_prompt = generate_cover_art_prompt(
        title, genre or "Electronic", "energetic", artist_key
    )

    con.execute("""
        INSERT INTO releases (
            title, artist_key, release_type, upc, release_date,
            cover_art_prompt, track_ids, status, created_at, updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, 'draft', ?, ?)
    """, (title, artist_key, release_type, upc, release_date,
          cover_prompt, json.dumps(ids), now, now))
    con.commit()
    con.close()

    return {
        "status": "created",
        "title": title,
        "release_type": release_type,
        "upc": upc,
        "cover_art_prompt": cover_prompt,
    }


# --------------------------------------------------------------------------
# Dashboard (HTML)
# --------------------------------------------------------------------------

@app.get("/", response_class=HTMLResponse)
async def dashboard():
    """HTML dashboard for music distribution."""
    con = get_db()
    tracks_total = con.execute("SELECT COUNT(*) FROM tracks").fetchone()[0]
    queue_pending = con.execute("SELECT COUNT(*) FROM distribution_queue WHERE status = 'pending'").fetchone()[0]
    queue_live = con.execute("SELECT COUNT(*) FROM distribution_queue WHERE status = 'live'").fetchone()[0]
    total_streams = con.execute("SELECT COALESCE(SUM(streams), 0) FROM revenue").fetchone()[0]
    total_revenue = con.execute("SELECT COALESCE(SUM(revenue_usd), 0) FROM revenue").fetchone()[0]

    recent_tracks = con.execute(
        "SELECT id, title, artist_name, genre, status, created_at FROM tracks ORDER BY created_at DESC LIMIT 10"
    ).fetchall()

    platform_rows = con.execute("SELECT * FROM platform_accounts ORDER BY platform").fetchall()
    con.close()

    tracks_html = ""
    for t in recent_tracks:
        status_color = {
            "new": "#3b82f6", "queued": "#f59e0b",
            "distributed": "#10b981", "failed": "#ef4444",
        }.get(t["status"], "#6b7280")
        tracks_html += f"""
        <tr>
            <td>{t['id']}</td>
            <td><strong>{t['title']}</strong></td>
            <td>{t['artist_name']}</td>
            <td>{t['genre']}</td>
            <td><span style="color:{status_color};font-weight:bold">{t['status'].upper()}</span></td>
            <td>{t['created_at'][:10]}</td>
        </tr>"""

    platforms_html = ""
    for p in platform_rows:
        status_color = {
            "not_started": "#6b7280", "in_progress": "#f59e0b",
            "ready": "#3b82f6", "active": "#10b981",
        }.get(p["setup_status"], "#6b7280")
        name = PLATFORMS.get(p["platform"], {}).get("name", p["platform"])
        platforms_html += f"""
        <tr>
            <td><strong>{name}</strong></td>
            <td><span style="color:{status_color};font-weight:bold">{p['setup_status'].upper()}</span></td>
            <td>{p['account_email'] or '-'}</td>
            <td>{p['profile_url'] or '-'}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hive Music Distributor</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
               background: #0f172a; color: #e2e8f0; padding: 20px; }}
        h1 {{ color: #818cf8; margin-bottom: 8px; }}
        h2 {{ color: #a5b4fc; margin: 24px 0 12px; }}
        .subtitle {{ color: #94a3b8; margin-bottom: 24px; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
                  gap: 16px; margin-bottom: 24px; }}
        .stat {{ background: #1e293b; border-radius: 12px; padding: 20px;
                 border: 1px solid #334155; }}
        .stat-value {{ font-size: 2em; font-weight: bold; color: #818cf8; }}
        .stat-label {{ color: #94a3b8; margin-top: 4px; }}
        table {{ width: 100%; border-collapse: collapse; background: #1e293b;
                 border-radius: 12px; overflow: hidden; margin-bottom: 24px; }}
        th {{ background: #334155; padding: 12px 16px; text-align: left;
              color: #a5b4fc; font-weight: 600; }}
        td {{ padding: 10px 16px; border-bottom: 1px solid #1e293b; }}
        tr:hover {{ background: #334155; }}
        .api-link {{ color: #818cf8; text-decoration: none; }}
        .api-link:hover {{ text-decoration: underline; }}
        .api-list {{ background: #1e293b; border-radius: 12px; padding: 20px;
                     border: 1px solid #334155; }}
        .api-list a {{ display: block; padding: 6px 0; color: #818cf8;
                       text-decoration: none; font-family: monospace; }}
        .api-list a:hover {{ color: #c7d2fe; }}
    </style>
</head>
<body>
    <h1>Hive Music Distributor</h1>
    <p class="subtitle">Music distribution management — port {PORT}</p>

    <div class="stats">
        <div class="stat">
            <div class="stat-value">{tracks_total}</div>
            <div class="stat-label">Total Tracks</div>
        </div>
        <div class="stat">
            <div class="stat-value">{queue_pending}</div>
            <div class="stat-label">Pending Distribution</div>
        </div>
        <div class="stat">
            <div class="stat-value">{queue_live}</div>
            <div class="stat-label">Live on Platforms</div>
        </div>
        <div class="stat">
            <div class="stat-value">{total_streams:,}</div>
            <div class="stat-label">Total Streams</div>
        </div>
        <div class="stat">
            <div class="stat-value">${total_revenue:.2f}</div>
            <div class="stat-label">Total Revenue</div>
        </div>
    </div>

    <h2>Platform Status</h2>
    <table>
        <tr><th>Platform</th><th>Status</th><th>Email</th><th>Profile URL</th></tr>
        {platforms_html}
    </table>

    <h2>Recent Tracks</h2>
    <table>
        <tr><th>ID</th><th>Title</th><th>Artist</th><th>Genre</th><th>Status</th><th>Added</th></tr>
        {tracks_html}
    </table>

    <h2>API Endpoints</h2>
    <div class="api-list">
        <a href="/health">GET /health</a>
        <a href="/api/platforms">GET /api/platforms — all platforms with setup guides</a>
        <a href="/api/tracks">GET /api/tracks — all tracked music</a>
        <a href="/api/queue">GET /api/queue — distribution queue</a>
        <a href="/api/distributed">GET /api/distributed — live tracks</a>
        <a href="/api/revenue">GET /api/revenue — revenue by platform</a>
        <a href="/api/strategy">GET /api/strategy — distribution strategy</a>
        <a href="/api/artists">GET /api/artists — artist profiles</a>
        <a href="/api/stats">GET /api/stats — overall statistics</a>
        <a href="/api/releases">GET /api/releases — release groupings</a>
        <a href="/docs">Swagger UI — interactive API docs</a>
    </div>
</body>
</html>"""


# ==========================================================================
# MAIN
# ==========================================================================

if __name__ == "__main__":
    init_db()
    uvicorn.run(app, host="0.0.0.0", port=PORT, log_level="info")
